version: '3.9'

services:
  database:
    container_name: database
    image: mysql:8.0.33
    restart: always
    env_file:
      - .env # Use the .env file for environment variables
    environment:
      MYSQL_DATABASE: parkinglot
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_PORT: 3307
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
        - parkinglotNetwork

  parkingLot:
    image: 'parkinglot-app:latest'
    build:
      context: .
      dockerfile: DockerFile
    container_name: parkinglot
    restart: on-failure
    env_file:
      - .env
    ports:
      - "1222:1222"
    environment:
      - server.port=1222
      - spring.datasource.username=${DATABASE_USERNAME}
        - spring.datasource.password=${DATABASE_PASSWORD}
        - PARKING_LOT_DB_IP=database
        - PARKING_LOT_DB_PORT=3307
        - spring.datasource.url=jdbc:mysql://host.docker.internal:3307/parkinglot
    depends_on:
      - database
    networks:
        - parkinglotNetwork

networks:
  parkinglotNetwork:
